#!/usr/bin/perl

# setup_epics_common
#
# Builds a display search path for MEDM, caQtDM, or pyDM by automatically
# discovering screen file directories within all support modules referenced
# by the IOC's configure/RELEASE file.
#
# Usage:
#   As a Perl module (from ioc.pl command modules):
#     require "$TOP/setup_epics_common";
#     my $path = build_display_path($epics_app, $display_manager);
#
#   As a standalone script (for eval from bash):
#     eval $(perl setup_epics_common <display_manager> <epics_app>)

use strict;
use Cwd 'abs_path';

# Directories to skip during search -- build artifacts, VCS,
# test/example code, documentation, and iocBoot directories.
my %SKIP_DIRS = map { $_ => 1 } qw(
    .git .svn .hg
    bin lib include dbd db
    iocBoot documentation docs
    autoconvert
);

# Prefixes of directory names to skip (test apps, examples, etc.)
my @SKIP_PREFIXES = qw(test example);


###############################################################################
# Parse a RELEASE file and return a hash of MODULE => PATH
#
# This is equivalent to the logic in release.pl but returns the data as a
# hash rather than printing it.
###############################################################################

sub parse_release
{
    my ($file, $applications) = @_;

    if (-r "$file")
    {
        open(my $fh, "<", "$file") or return;

        while (my $line = <$fh>)
        {
            next if ($line =~ /^\s*#/);

            chomp($line);
            $line =~ s/\r//g;

            # Test for "include" / "-include" directives
            if ($line =~ /^(-?include)\s+(.*)/)
            {
                my $inc_path = $2;

                # Resolve $(MACRO) references in the include path
                if ($inc_path =~ /\$\((\w+)\)(.*)/)
                {
                    my $macro = $1;
                    my $rest  = $2;

                    if (exists $applications->{$macro} && $applications->{$macro} ne "")
                    {
                        $inc_path = $applications->{$macro} . $rest;
                    }
                    else
                    {
                        next;    # macro not yet defined, skip
                    }
                }

                parse_release($inc_path, $applications);
            }
            elsif ($line =~ /^(\w+)\s*=\s*(.*)/)
            {
                my $key = $1;
                my $val = $2;

                # Resolve $(MACRO) references in the value
                if ($val =~ /\$\((\w+)\)(.*)/)
                {
                    my $macro = $1;
                    my $rest  = $2;

                    if (exists $applications->{$macro} && $applications->{$macro} ne "")
                    {
                        $val = $applications->{$macro} . $rest;
                    }
                }

                $key =~ s/^\s+|\s+$//g;

                if ($key ne "")
                {
                    $applications->{$key} = $val;
                }
            }
        }

        close($fh);
    }
}


###############################################################################
# Depth-limited directory scanner.  Searches for directories containing
# files with the given extension.  When a matching directory is found,
# its /autoconvert subdirectory is also added (if it exists) but not
# searched further.  Skips build output, test, and documentation dirs.
#
#   $dir       - Directory to search
#   $extension - File extension to look for (e.g., "adl", "ui")
#   $max_depth - Maximum directory depth to descend
#   $results   - Array ref to append found directories to
###############################################################################

sub _search_depth
{
    my ($dir, $extension, $max_depth, $results) = @_;

    return if $max_depth < 0;

    # Check if this directory contains screen files
    my @files = glob("$dir/*.$extension");

    if (@files)
    {
        push @$results, $dir;

        # Also add /autoconvert if it exists (but don't search into it)
        if (-d "$dir/autoconvert")
        {
            push @$results, "$dir/autoconvert";
        }

        return;    # Don't recurse deeper once we've found screen files
    }

    # No screen files here, but check if autoconvert/ has them
    # (some modules only have auto-converted screens, not hand-crafted ones)
    if (-d "$dir/autoconvert")
    {
        my @ac_files = glob("$dir/autoconvert/*.$extension");

        if (@ac_files)
        {
            push @$results, "$dir/autoconvert";
            return;
        }
    }

    # Recurse into subdirectories
    return if $max_depth == 0;

    opendir(my $dh, $dir) or return;

    my @subdirs = grep {
        my $name = $_;

        $name ne '.' && $name ne '..'
        && !$SKIP_DIRS{$name}
        && $name !~ /^O\./
        && !grep { $name =~ /^${_}/i } @SKIP_PREFIXES;
    } readdir($dh);

    closedir($dh);

    for my $subdir (sort @subdirs)
    {
        my $full = "$dir/$subdir";
        next unless -d $full;
        _search_depth($full, $extension, $max_depth - 1, $results);
    }
}


###############################################################################
# Discover screen file directories for a given file extension within a
# module path.  Searches to a depth of 3 directories, which covers all
# standard synApps screen directory layouts:
#
#   depth 1: streamApp                    (StreamDevice)
#   depth 2: op/adl, opi/medm            (devIocStats, asyn)
#   depth 3: *App/op/adl, *App/opi/adl   (most modules)
#
# If the module contains a 'modules/' subdirectory (e.g., motor), that
# subdirectory is also searched to depth 3, covering layouts like:
#   modules/<submod>/<name>App/op/adl     (motor submodules)
###############################################################################

sub find_screen_dirs
{
    my ($module_path, $extension) = @_;

    my @found;

    return @found unless (-d $module_path);

    # Search to depth 3 from the module root
    _search_depth($module_path, $extension, 3, \@found);

    # If a 'modules/' subdirectory exists, search each submodule within
    # it to depth 3 (covers motor-style layouts like
    # modules/<submod>/<name>App/op/adl)
    if (-d "$module_path/modules")
    {
        opendir(my $dh, "$module_path/modules") or return sort @found;

        for my $submod (sort readdir($dh))
        {
            next if $submod eq '.' || $submod eq '..';
            my $submod_path = "$module_path/modules/$submod";
            next unless -d $submod_path;
            _search_depth($submod_path, $extension, 3, \@found);
        }

        closedir($dh);
    }

    return sort @found;
}


###############################################################################
# Build the complete display path for a given display manager.
#
#   $epics_app      - Top level IOC directory (TOP)
#   $display_manager - "medm", "caqtdm", or "pydm"
#
# Scans $epics_app first (so the local application's screens appear at the
# front of the path), then scans all support modules from configure/RELEASE.
#
# Returns the colon-separated display path string.
###############################################################################

sub build_display_path
{
    my ($epics_app, $display_manager) = @_;

    # Determine file extension to search for
    my $extension;

    if    ($display_manager eq "medm")    { $extension = "adl"; }
    elsif ($display_manager eq "caqtdm")  { $extension = "ui"; }
    elsif ($display_manager eq "pydm")    { $extension = "ui"; }
    else                                  { return ""; }

    # Parse RELEASE to get all module paths
    my %applications;
    $applications{"TOP"} = $epics_app;

    if (defined $ENV{GATEWAY} && $ENV{GATEWAY} ne "")
    {
        $applications{"GATEWAY"} = $ENV{GATEWAY};
    }

    parse_release("$epics_app/configure/RELEASE", \%applications);

    # Remove non-module entries
    delete $applications{"TOP"};
    delete $applications{"SUPPORT"};
    delete $applications{"EPICS_BASE"};

    # Scan the local application directory first so its screens take priority
    my @path_components;

    if (-d $epics_app)
    {
        my @local_dirs = find_screen_dirs($epics_app, $extension);
        push @path_components, @local_dirs;
    }

    # Discover screen directories in each support module
    foreach my $mod (sort keys %applications)
    {
        my $mod_path = $applications{$mod};
        next unless (-d $mod_path);

        my @dirs = find_screen_dirs($mod_path, $extension);
        push @path_components, @dirs;
    }

    return join(":", @path_components);
}


###############################################################################
# If run as a standalone script, output shell export commands for eval
###############################################################################

if (!caller())
{
    my $display_manager = $ARGV[0] // "";
    my $epics_app       = $ARGV[1] // $ENV{EPICS_APP} // ".";

    my $path = build_display_path($epics_app, $display_manager);

    if ($display_manager eq "medm")
    {
        if (defined $ENV{EPICS_DISPLAY_PATH} && $ENV{EPICS_DISPLAY_PATH} ne "")
        {
            print "export EPICS_DISPLAY_PATH=$path:\$EPICS_DISPLAY_PATH\n";
        }
        else
        {
            print "export EPICS_DISPLAY_PATH=$path\n";
        }
    }
    elsif ($display_manager eq "caqtdm")
    {
        if (defined $ENV{CAQTDM_DISPLAY_PATH} && $ENV{CAQTDM_DISPLAY_PATH} ne "")
        {
            print "export CAQTDM_DISPLAY_PATH=$path:\$CAQTDM_DISPLAY_PATH\n";
        }
        else
        {
            print "export CAQTDM_DISPLAY_PATH=$path\n";
        }
    }
    elsif ($display_manager eq "pydm")
    {
        if (defined $ENV{PYDM_DISPLAYS_PATH} && $ENV{PYDM_DISPLAYS_PATH} ne "")
        {
            print "export PYDM_DISPLAYS_PATH=$path:\$PYDM_DISPLAYS_PATH\n";
        }
        else
        {
            print "export PYDM_DISPLAYS_PATH=$path\n";
        }
    }
}

1;
