#!/bin/csh -f

# For drag-and-drop workaround:
#alias xclip /APSshare/bin/xclip
setenv PATH ${PATH}:/APSshare/bin
unsetenv MEDM_EXEC_LIST
setenv CAQTDM_EXEC_LIST 'Probe;probe &P &:UI File;echo &A:PV Name(s);echo &P:Copy PV name; echo -n &P| xclip -i -sel clip:Paste PV name;caput &P `xclip -o -sel clip`'

setenv EPICS_APP /home/oxygen/MOONEY/epics/synApps/support/xxx
setenv EPICS_APP_UI_DIR ${EPICS_APP}/xxxApp/op/ui

set output = `perl $EPICS_APP/release.pl $EPICS_APP`
$output

#######################################
# Prepare CAQTDM_DISPLAY_PATH
# QTDMDP is temporary CAQTDM_DISPLAY_PATH
#
setenv QTDMDP  .
if ( ${?EPICS_APP_UI_DIR} ) then
	setenv QTDMDP ${QTDMDP}:${EPICS_APP_UI_DIR}
endif
if ( ${?AREA_DETECTOR} ) then
	setenv QTDMDP ${QTDMDP}:${AREA_DETECTOR}/ADApp/op/ui
endif
if ( ${?ADCORE} ) then
	setenv QTDMDP ${QTDMDP}:${ADCORE}/ADApp/op/ui
	setenv QTDMDP ${QTDMDP}:${ADCORE}/ADApp/op/ui/autoconvert
endif
if ( ${?ASYN} ) then
	setenv QTDMDP ${QTDMDP}:${ASYN}/opi/caqtdm
endif
if ( ${?ALIVE} ) then
	setenv QTDMDP ${QTDMDP}:${ALIVE}/aliveApp/op/ui
endif
if ( ${?AUTOSAVE} ) then
	setenv QTDMDP ${QTDMDP}:${AUTOSAVE}/asApp/op/ui
endif
if ( ${?BUSY} ) then
	setenv QTDMDP ${QTDMDP}:${BUSY}/busyApp/op/ui
endif
if ( ${?CALC} ) then
	setenv QTDMDP ${QTDMDP}:${CALC}/calcApp/op/ui
endif
if ( ${?CAMAC} ) then
	setenv QTDMDP ${QTDMDP}:${CAMAC}/camacApp/op/ui
endif
if ( ${?CAPUTRECORDER} ) then
	setenv QTDMDP ${QTDMDP}:${CAPUTRECORDER}/caputRecorderApp/op/ui
endif
if ( ${?DAC128V} ) then
	setenv QTDMDP ${QTDMDP}:${DAC128V}/dac128VApp/op/ui
endif
if ( ${?DELAYGEN} ) then
	setenv QTDMDP ${QTDMDP}:${DELAYGEN}/delaygenApp/op/ui
endif
if ( ${?DEVIOCSTATS} ) then
	setenv QTDMDP ${QTDMDP}:${DEVIOCSTATS}/op/ui
endif
if ( ${?DXP} ) then
	setenv QTDMDP ${QTDMDP}:${DXP}/dxpApp/op/ui
endif
if ( ${?IP} ) then
	setenv QTDMDP ${QTDMDP}:${IP}/ipApp/op/ui
endif
if ( ${?IP330} ) then
	setenv QTDMDP ${QTDMDP}:${IP330}/ip330App/op/ui
endif
if ( ${?IPUNIDIG} ) then
	setenv QTDMDP ${QTDMDP}:${IPUNIDIG}/ipUnidigApp/op/ui
endif
if ( ${?LOVE} ) then
	setenv QTDMDP ${QTDMDP}:${LOVE}/loveApp/op/ui
endif
if ( ${?MCA} ) then
	setenv QTDMDP ${QTDMDP}:${MCA}/mcaApp/op/ui
endif
if ( ${?MEASCOMP} ) then
	setenv QTDMDP ${QTDMDP}:${MEASCOMP}/measCompApp/op/ui
endif
if ( ${?MODBUS} ) then
	setenv QTDMDP ${QTDMDP}:${MODBUS}/modbusApp/op/ui
endif
if ( ${?MOTOR} ) then
	setenv QTDMDP ${QTDMDP}:${MOTOR}/motorApp/op/ui
endif
if ( ${?OPTICS} ) then
	setenv QTDMDP ${QTDMDP}:${OPTICS}/opticsApp/op/ui
endif
if ( ${?QUADEM} ) then
	setenv QTDMDP ${QTDMDP}:${QUADEM}/quadEMApp/op/ui
endif
if ( ${?SOFTGLUE} ) then
	setenv QTDMDP ${QTDMDP}:${SOFTGLUE}/softGlueApp/op/ui
endif
if ( ${?SSCAN} ) then
	setenv QTDMDP ${QTDMDP}:${SSCAN}/sscanApp/op/ui
endif
if ( ${?STD} ) then
	setenv QTDMDP ${QTDMDP}:${STD}/stdApp/op/ui
endif
if ( ${?VAC} ) then
	setenv QTDMDP ${QTDMDP}:${VAC}/vacApp/op/ui
endif
if ( ${?VME} ) then
	setenv QTDMDP ${QTDMDP}:${VME}/vmeApp/op/ui
endif

setenv QTDMDP ${QTDMDP}:/APSshare/uisys/sr/id

if (! ${?CAQTDM_DISPLAY_PATH}) then
setenv CAQTDM_DISPLAY_PATH ${QTDMDP}
else
setenv CAQTDM_DISPLAY_PATH ${QTDMDP}:${CAQTDM_DISPLAY_PATH}
endif

# This should agree with the environment variable set by the ioc
# see 'putenv "EPICS_CA_MAX_ARRAY_BYTES=64008"' in iocBoot/ioc<target>/st.cmd
#setenv EPICS_CA_MAX_ARRAY_BYTES 64008
# for areaDetector
setenv EPICS_CA_MAX_ARRAY_BYTES 2000100

cd ${EPICS_APP_UI_DIR}

setenv START_PUTRECORDER ${EPICS_APP}/start_putrecorder
setenv MACROS_PY ${EPICS_APP_UI_DIR}/../python/macros.py
setenv EDITOR nedit

setenv QT_PLUGIN_PATH /APSshare/caqtdm/lib:/APSshare/caqtdm/plugins
alias caQtDM /APSshare/caqtdm/bin/caQtDM

caQtDM xxx.ui&

#sleep 1
#caQtDM -attach -macro "P=xxx:,S=scan1" -dg +500+300 scan.ui
#sleep 1
#caQtDM -attach -macro "P=xxx:,S=scan2" -dg +100+300 scan.ui
#sleep 1
#caQtDM -attach -macro "P=xxx:,M=m2" -dg 1x1+1000+300 motorx.ui
