#!/bin/sh

# start, or restart, caputRecorder.py

PREFIX=$1

EPICS_APP=/home/oxygen/MOONEY/epics/synApps/support/xxx
MACROS_PY_DIR=${EPICS_APP}/xxxApp/op/python

output=`perl -s ${EPICS_APP}/release.pl -form=bash ${EPICS_APP}`
eval $output

#echo "CAPUTRECORDER=", $CAPUTRECORDER
CAPUTRECORDER_PY=${CAPUTRECORDER}/caputRecorderApp/op/python/caputRecorder.py

arch=`uname -p`
COMMAND="/APSshare/anaconda/${arch}/bin/python ${CAPUTRECORDER_PY}"
#COMMAND="/APSshare/epd/rh6-x86_64/bin/python ${CAPUTRECORDER_PY}"

export PYTHONPATH=${MACROS_PY_DIR}:$PYTHONPATH
namePrefix=$( echo $PREFIX | sed s/://g )
MACROS_PY=${MACROS_PY_DIR}/"macros_"${namePrefix}.py

# start caputRecorder.py
$COMMAND ${PREFIX} ${MACROS_PY}&

# start caputRecorder.py with more prefixes
#$COMMAND ${PREFIX} yyy: zzz: ${MACROS_PY}&
