#!/bin/csh -f

setenv EPICS_APP /home/oxygen/MOONEY/epics/synApps/support/xxx
setenv EPICS_APP_NAME xxx

# define environment variables for MEDM, caQtDM, and Probe
source ./setup_epics_common

# For drag-and-drop workaround:
# get xclip in path
setenv PATH ${PATH}:/APSshare/bin
unsetenv MEDM_EXEC_LIST
setenv CAQTDM_EXEC_LIST 'Probe;probe &P &:UI File;echo &A:PV Name(s);echo &P:Copy PV name; echo -n &P| xclip -i -sel clip:Paste PV name;caput &P `xclip -o -sel clip`'

cd ${EPICS_APP_UI_DIR}

alias caQtDM /APSshare/bin/caQtDM
caQtDM -noMsg ${EPICS_APP_NAME}.ui&
