#!/usr/bin/perl

use strict;
use FindBin;
use Cwd 'abs_path';
use File::Basename;

# Resolve EPICS_APP to the real directory of this script (follows symlinks)
my $EPICS_APP = $FindBin::RealBin;

# IOC screen directory and default file
my $EPICS_APP_UI_DIR  = "$EPICS_APP/xxxApp/op/ui";
my $DEFAULT_UI_FILE   = $ARGV[0] // $ENV{DEFAULT_UI_FILE} // "xxx.ui";
my $UI_FILE_MACROS    = $ARGV[1] // "P=xxx:";

# Build the display path using setup_epics_common
require "$EPICS_APP/setup_epics_common";
my $display_path = build_display_path($EPICS_APP, "caqtdm", $EPICS_APP_UI_DIR);

# Set environment
$ENV{CAQTDM_DISPLAY_PATH} = defined $ENV{CAQTDM_DISPLAY_PATH} && $ENV{CAQTDM_DISPLAY_PATH} ne ""
    ? "$display_path:$ENV{CAQTDM_DISPLAY_PATH}"
    : $display_path;

#######################################
# optional: add support directories not associated with environment variables

# if (-d "/APSshare/uisys/sr/id")
# {
#     $ENV{CAQTDM_DISPLAY_PATH} .= ":/APSshare/uisys/sr/id";
# }


#######################################
# optional: support for PVs with large data sizes, such as areaDetector
# This should agree with the environment variable set by the IOC
# see 'epicsEnvSet "EPICS_CA_MAX_ARRAY_BYTES"' in settings.iocsh

$ENV{EPICS_CA_MAX_ARRAY_BYTES} //= 8000100;


#######################################
# optional: override system default environment variables for Qt and Qwt
# These override system defaults for Qt, Qwt
# Because I'm using a local copy of Qt/Qwt, and not the system
# copy, I need to set some environment variables

#my $OVERRIDE_QT_BASE = "/home/oxygen/MOONEY/Download/Qt";
#$ENV{QTDIR} = "$OVERRIDE_QT_BASE/qt-4.8.4";
#$ENV{QT_PLUGIN_PATH} = "";
#$ENV{QT_PLUGIN_PATH} .= ":$OVERRIDE_QT_BASE/qt-4.8.4/plugins";
#$ENV{QT_PLUGIN_PATH} .= ":$OVERRIDE_QT_BASE/qwt-6.0/designer/plugins/designer";


#######################################
# optional: other environment variables that may need local definitions
# these are copied from caQtDM's source for startDM_Local

#$ENV{QTCONTROLS_LIBS} = getcwd() . "/caQtDM_Binaries";
#$ENV{QTBASE} = $ENV{QTCONTROLS_LIBS};
#$ENV{QT_PLUGIN_PATH} = $ENV{QTBASE};

# For drag-and-drop workaround at APS, need /APSshare/bin/xclip
$ENV{CAQTDM_EXEC_LIST} = 'Probe;probe &P &:UI File;echo &A:PV Name(s);echo &P:Copy PV name; echo -n &P| xclip -i -sel clip:Paste PV name;caput &P `xclip -o -sel clip`';

$ENV{START_PUTRECORDER} = "$EPICS_APP/start_putrecorder";
$ENV{MACROS_PY}         = "$EPICS_APP_UI_DIR/../python/macros.py";
$ENV{EDITOR}          //= "nedit";

if (-d "/APSshare/caqtdm")
{
    $ENV{PATH} = "$ENV{PATH}:/APSshare/bin";
    $ENV{QT_PLUGIN_PATH}  = "/APSshare/caqtdm/plugins";
    $ENV{LD_LIBRARY_PATH} = "/APSshare/caqtdm/lib";
    $ENV{LD_LIBRARY_PATH} .= ":" . ($ENV{EPICS_BASE} // "") . "/lib/linux-x86_64";
}
else
{
    $ENV{QT_PLUGIN_PATH} = "/usr/local/epics/extensions/lib/linux-x86_64";
}


#######################################
# optional: access to ioctim and bcdapc15

#$ENV{EPICS_CA_ADDR_LIST} = "164.54.53.99 164.54.54.88";


#######################################
# start caQtDM

exec("/APSshare/bin/caQtDM", "-style", "plastique", "-noMsg", "-macro", $UI_FILE_MACROS, $DEFAULT_UI_FILE);
