#!/usr/bin/perl

use strict;
use FindBin;
use Cwd 'abs_path';
use File::Basename;

# Resolve EPICS_APP to the real directory of this script (follows symlinks)
my $EPICS_APP = $FindBin::RealBin;

# IOC screen directory and default file
my $EPICS_APP_ADL_DIR = "$EPICS_APP/xxxApp/op/adl";
my $DEFAULT_UI_FILE   = $ARGV[0] // $ENV{DEFAULT_UI_FILE} // "xxx.adl";
my $UI_FILE_MACROS    = $ARGV[1] // "P=xxx:";

# Build the display path using setup_epics_common
require "$EPICS_APP/setup_epics_common";
my $display_path = build_display_path($EPICS_APP, "medm", $EPICS_APP_ADL_DIR);

# Set environment
$ENV{EPICS_DISPLAY_PATH} = defined $ENV{EPICS_DISPLAY_PATH} && $ENV{EPICS_DISPLAY_PATH} ne ""
    ? "$display_path:$ENV{EPICS_DISPLAY_PATH}"
    : $display_path;

$ENV{MEDM_EXEC_LIST}   //= 'Probe;probe &P &';
$ENV{START_PUTRECORDER}   = "$EPICS_APP/start_putrecorder";
$ENV{MACROS_PY}           = "$EPICS_APP_ADL_DIR/../python/macros.py";
$ENV{EDITOR}            //= "nedit";

# This should agree with the environment variable set by the IOC
# see 'epicsEnvSet "EPICS_CA_MAX_ARRAY_BYTES"' in settings.iocsh
$ENV{EPICS_CA_MAX_ARRAY_BYTES} //= 64008;

# Start MEDM
exec("medm", "-macro", $UI_FILE_MACROS, "-x", $DEFAULT_UI_FILE);
