#!/usr/bin/perl

use strict;
use FindBin;
use Cwd 'abs_path';
use File::Basename;

# Resolve EPICS_APP to the real directory of this script (follows symlinks)
my $EPICS_APP = $FindBin::RealBin;

# IOC screen directory and default file
my $EPICS_APP_UI_DIR  = "$EPICS_APP/xxxApp/op/bob/autoconvert";
my $DEFAULT_UI_FILE   = $ARGV[0] // $ENV{DEFAULT_UI_FILE} // "ioc_motors.bob";
my $UI_FILE_MACROS    = $ARGV[1] // "P=xxx:";

#######################################
# optional: support for PVs with large data sizes, such as areaDetector
# This should agree with the environment variable set by the IOC
# see 'epicsEnvSet "EPICS_CA_MAX_ARRAY_BYTES"' in settings.iocsh

$ENV{EPICS_CA_MAX_ARRAY_BYTES} //= 8000100;

$ENV{START_PUTRECORDER} = "$EPICS_APP/start_putrecorder";
$ENV{MACROS_PY}         = "$EPICS_APP_UI_DIR/../python/macros.py";
$ENV{EDITOR}          //= "nedit";


#######################################
# start CSS-phoebus

exec("/APSshare/bin/phoebus",
    "-layout", "$EPICS_APP/phoebus.layout",
    "-resource", "file:${EPICS_APP_UI_DIR}/${DEFAULT_UI_FILE}?${UI_FILE_MACROS}&target=window");
