TOP = ../..
include $(TOP)/configure/CONFIG

#ARCH = win32-x86
#ARCH = windows-x64-static
#ARCH = windows-x64-debug
#ARCH = windows-x64
#ARCH = cygwin-x86
#ARCH = linux-x86
ARCH = linux-x86_64
#ARCH = vxWorks-ppc32
#ARCH = vxWorks694-ppc32
#ARCH = vxWorks-ppc603

#TARGETS = cdCommands
TARGETS = envPaths
#TARGETS = envPaths dllPath.bat

include $(TOP)/configure/RULES.ioc
