# Makefile.Host
TOP = ../../..
include $(TOP)/config/CONFIG_APP
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

DBDEXPAND = xxxInclude.dbd
DBDNAME = xxxApp.dbd

include $(TOP)/config/RULES.Host
#----------------------------------------
#  ADD RULES AFTER THIS LINE
